### ISSUE TITLE
Redirect bug

### ISSUE THREAD

**Issue by GauthamGoli** [MikeMcQuaid/mikemcquaid.github.io#4]
[How To Run A Google Summer Of Code Project On GitHub](http://mikemcquaid.com/2017/02/06/how-to-run-a-google-summer-of-code-project-on-github/) Post doesn't redirect to https://github.com/blog/2312-how-to-run-a-google-summer-of-code-project-on-github

**Comment by MikeMcQuaid** [comment]
Thanks; a change in the redirect plugin broke this. Fixed now!
